const product_types = [
  "Hair Oil & Serum",
  "Water & Fridge Bottles",
  "Lamp & Lamp Oil",
  "Laundry, Storage Baskets",
  "Bathing Bars & Soaps",
  "Disinfectant Spray & Cleaners",
  "Face Care",
  "Hand Wash & Sanitizers",
  "Shampoo & Conditioner",
  "Utensil Scrub-Pad, Glove",
  "Flours & Pre-Mixes",
  "Luxury Chocolates, Gifts",
  "Floor & Other Cleaners",
  "Mosquito Repellent",
  "Soap Cases & Dispensers",
  "Aromatherapy",
  "Roasted Seeds & Nuts",
  "Tofu",
  "Tools & Accessories",
  "Imported Noodles",
  "Other Dry Fruits",
  "Gourmet Tea & Tea Bags",
  "Choppers & Graters",
  "Casserole",
  "Granola & Cereal Bars",
  "Frozen Veg Snacks",
  "Lip Care",
  "Juices",
  "Bakery Biscuits, Cookies",
  "Men's Deodorants",
  "Green Tea",
  "Containers Sets",
  "Whole Spices",
  "Blended Masalas",
  "Chocolates",
  "Eau De Toilette",
  "Cookies, Biscotti, Wafer",
  "Steel Lunch Boxes",
  "Olive, Jalapeno, Gherkin",
  "Organic Rice, Other Rice",
  "Shaving Care",
  "Imported Cleaners",
  "Thai & Asian Sauces",
  "Chutney Powder",
  "Cooking Pastes",
  "Gourmet Juices & Drinks",
  "Face & Body",
  "Beans & Pulses",
  "Papads, Ready To Fry",
  "Hair & Scalp Treatment",
  "Baby Health",
  "Kitchen Tools & Other Accessories",
  "Pet Meals & Treats",
  "Chocolate, Peanut Spread",
  "Marie, Health, Digestive",
  "Electric Toothbrush",
  "Toothpaste",
  "Toothbrush",
  "Chips & Corn Snacks",
  "Organic Dals & Pulses",
  "Agarbatti, Incense Sticks",
  "Tawa & Sauce Pan",
  "Flavoured, Soya Milk",
  "Namkeen & Savoury Snacks",
  "Steel Storage Containers",
  "Diapers",
  "Shower Gel & Body Wash",
  "Umbrella",
  "Kadai & Fry Pans",
  "Baby Food",
  "Body Care",
  "Organic Masalas & Spices",
  "Leaf & Dust Tea",
  "Rusks",
  "Air Freshener",
  "Lunch Boxes",
  "Sunflower, Rice Bran Oil",
  "Cream Biscuits & Wafers",
  "Glassware",
  "Breakfast & Snack Mixes",
  "Plates & Tumblers",
  "Organic Edible Oil, Ghee",
  "Lime & Mango Pickle",
  "Powdered Spices",
  "Flakes",
  "Flavoured & Other Oils",
  "Hair Removal",
  "Pure, Pomace Olive Oil",
  "Hair Color",
  "Bibs & Napkins",
  "Exam Pads & Pencil Box",
  "Sports & Energy Drinks",
  "CFL & Led Bulbs",
  "Sugar & Jaggery",
  "Heat & Eat Ready Meals",
  "Gourmet Bread",
  "Notebooks, Files, Folders",
  "Chikki & Gajjak",
  "Home Baking",
  "Strainer, Ladle, Spatula",
  "Balsamic & Cider Vinegar",
  "Baby Wipes",
  "Dustbins",
  "Pressure Cookers",
  "Supplements & Proteins",
  "Herbs, Seasonings & Rubs",
  "Paneer, Tofu & Cream",
  "Nachos & Chips",
  "Exotic Sugar & Salt",
  "Salted Biscuits",
  "Marshmallow, Candy, Jelly",
  "Cotton & Ear Buds",
  "Health Drinks",
  "Frozen Vegetables",
  "Curry Paste, Coconut Milk",
  "Paper Napkin, Tissue Box",
  "Instant Noodles",
  "Cereals & Millets",
  "Basmati Rice",
  "Cook And Serve",
  "Cold Drinks",
  "Dinner Sets",
  "Tea Bags",
  "Oats & Porridge",
  "Copper Utensils",
  "Salad Dressings",
  "Cereal & Granola Bars",
  "Organic Baby Food",
  "Chilli & Soya Sauce",
  "Bowls & Vessels",
  "Other Veg Pickle",
  "Muesli",
  "Tomatoes & Vegetables",
  "Crackers & Digestive",
  "Kids Cereal",
  "Toilet Cleaners",
  "Baking, Cake Decorations",
  "Dust Cloth & Wipes",
  "Ghee & Vanaspati",
  "Other Pooja Needs",
  "Vacuum Flask",
  "Choco & Nut Spread",
  "Caps, Balloons & Candles",
  "Pen, Pencils",
  "Plates & Bowls",
  "Organic & Cold Press Oil",
  "Face Masks & Safety Gears",
  "Eau De Parfum",
  "Dessert Mixes",
  "Toilet & Other Brushes",
  "Organic Flours",
  "Talc",
  "Toffee, Candy & Lollypop",
  "Bath Stool, Basin & Sets",
  "Colours & Crayons",
  "Jams, Marmalade, Spreads",
  "Sexual Wellness",
  "Kids (5+Yrs)",
  "Milk & Soya Drinks",
  "Honey & Maple Syrup",
  "Pastas & Spaghetti",
  "Baking Tools & Brushes",
  "Baby Powder",
  "Other Plastic Ware",
  "Cutlery, Spoon & Fork",
  "Body Sprays & Mists",
  "Toilet Paper",
  "Mops, Wipers",
  "Mouthwash",
  "Intimate Wash & Care",
  "Yogurt & Shrikhand",
  "International Chocolates",
  "Organic Sugar, Jaggery",
  "Tomato Ketchup & Sauces",
  "Exotic & Flavoured Tea",
  "Hangers, Clips & Rope",
  "Bath & Shower",
  "Herbs & Seasoning",
  "Kitchen, Glass & Drain",
  "Women's Deodorants",
  "Eye Care",
  "Honey",
  "Scissor, Glue & Tape",
  "Tinned, Packed Sweets",
  "Lighters",
  "Garbage Bags",
  "Everyday Medicine",
  "Soothers & Teethers",
  "Fresh Sweets",
  "Mints & Chewing Gum",
  "Ground Coffee",
  "Perfume",
  "Toor, Channa & Moong Dal",
  "Urad & Other Dals",
  "Eyes",
  "Fabric Pre, Post Wash",
  "Cup Noodles",
  "Non Veg Pickle",
  "Frozen Non-Veg Snacks",
  "Organic Dry Fruits",
  "Mayonnaise",
  "Bathing Accessories",
  "Gingelly Oil",
  "Rice & Other Flours",
  "Infant Formula",
  "Shoe Polish",
  "Cups, Mugs & Tumblers",
  "Cookies",
  "Buckets & Mugs",
  "Soups",
  "Sanitary Napkins",
  "Detergent Powder, Liquid",
  "Butter & Cream",
  "Kitchen Rolls",
  "Extra Virgin Olive Oil",
  "Vinegar",
  "Cheese",
  "Muffins & Cup Cakes",
  "Gardening Tools",
  "Pooja Thali & Bells",
  "Ice Creams",
  "Knives & Peelers",
  "Cooking Chocolate, Cocoa",
  "Jasmine & Sushi Rice",
  "Hair Care & Styling",
  "Poha, Sabudana & Murmura",
  "Men & Women",
  "Baby Oil & Shampoo",
  "Dishwash Bars & Powders",
  "Pasta & Macaroni",
  "Mukhwas",
  "Fertilizers & Pesticides",
  "Brooms & Dust Pans",
  "Camphor & Wicks",
  "Baby Oral Care",
  "Frozen Indian Breads",
  "Raw Rice",
  "Dishwash Liquids & Pastes",
  "Battery & Electrical",
  "Gift Sets",
  "Baby Creams & Lotions",
  "Pots, Planters & Trays",
  "Bakeware Accessories",
  "Instant Coffee",
  "Wall Hooks & Hangers",
  "Dips & Dressings",
  "Curd",
  "Mustard & Cheese Sauces",
  "Tea Cakes & Slice Cakes",
  "Baby Bath",
  "Spring Water",
  "Salts",
  "Sugarfree Sweeteners",
  "Cashews",
  "Trail & Cocktail Mixes",
  "Groundnut Oil",
  "Pastries & Brownies",
  "Soda & Cocktail Mix",
  "Tampons & Menstrual Cups",
  "Syrups & Concentrates",
  "Condensed, Powdered Milk",
  "Blended Cooking Oils",
  "Insect Repellent",
  "Other Edible Oils",
  "Talcum Powder",
  "Car Freshener",
  "Olive & Canola Oils",
  "Floss & Tongue Cleaner",
  "Car Polish & Cleaners",
  "Cookware Sets",
  "Face",
  "Hakka Noodles",
  "Panty Liners",
  "Eau De Cologne",
  "Detergent Bars",
  "Unsweetened, Cold Press",
  "Flavoured & Greek Yogurt",
  "Disposable Cups & Plates",
  "Moustache & Beard Care",
  "Jam, Conserve, Marmalade",
  "Vermicelli",
  "Sippers & Bottles",
  "Khari & Cream Rolls",
  "Sooji, Maida & Besan",
  "Decorations",
  "Children (2-5 Yrs)",
  "Instant Pasta",
  "Games & Calculators",
  "Pet Cleaning & Grooming",
  "Attar",
  "Boiled & Steam Rice",
  "Birthday & Party Cakes",
  "Premium Cookies",
  "Pet Toys",
  "Atta Whole Wheat",
  "Antiseptics & Bandages",
  "Aluminium Foil, Clingwrap",
  "Candles & Match Box",
  "Bath Salts & Oils",
  "Organic Millet & Flours",
  "Maternity Health Supplements",
  "Glucose Powder, Tablets",
  "Adult Diapers",
  "Milk",
  "Gourmet Flakes",
  "Baby Gift Sets",
  "Soya & Mustard Oils",
  "Wet Wipe, Pocket Tissues",
  "Glucose & Milk Biscuits",
  "Baby Laundry",
  "Pet Collars & Leashes",
  "Butter & Margarine",
  "Gift Wraps & Bags",
  "Baby Dishes & Utensils",
  "Pet Feeding Support",
  "Racks & Holders",
  "Non Alcoholic Drinks",
  "Bread Sticks & Lavash",
  "Dairy Free (Vegan)",
  "Books & Magazines",
  "Almonds",
  "Cloth Dryer & Iron Table",
  "Packaged Water",
  "Seeds & Sapling",
  "Buttermilk & Lassi",
  "Combos & Gift Sets",
  "Maternity Personal Care",
  "Panini, Focaccia & Pita",
  "Bagels & Baguette",
  "Diabetic Drinks",
  "Nails",
  "Cream & Cheese Spreads",
  "Regular & White Vinegar",
  "Gift Boxes",
  "Nursing Tools",
  "Seasonal Accessories",
  "Non-Alcoholic Beer, Wine",
  "Body Scrubs & Exfoliants",
  "Raisins",
  "Bakeware Moulds, Cutters",
  "Icetea, Non Aerated Drink",
  "Metal, Furniture Cleaner",
  "Cheese & Garlic Bread",
  "Hair Styling",
  "Makeup Accessories",
  "Erasers & Sharpeners",
  "Health Supplements",
  "Dry Shampoo & Conditioner",
  "Wine & Rice Vinegar",
  "Combs, Brushes, Clippers",
  "Canola & Rapeseed Oil",
  "Lips",
  "Holi Colours & Pichkari",
  "Baby Buds",
  "Baby Toys",
  "Nappies & Rash Cream",
  "Ayurveda",
  "Gourmet Popcorn",
];
