const subcategories = [
  "Hair Care",
  "Storage & Accessories",
  "Pooja Needs",
  "Bins & Bathroom Ware",
  "Bath & Hand Wash",
  "All Purpose Cleaners",
  "Skin Care",
  "Mops, Brushes & Scrubs",
  "Cooking & Baking Needs",
  "Chocolates & Biscuits",
  "Fresheners & Repellents",
  "Snacks, Dry Fruits, Nuts",
  "Dairy & Cheese",
  "Pasta, Soup & Noodles",
  "Dry Fruits",
  "Drinks & Beverages",
  "Kitchen Accessories",
  "Flask & Casserole",
  "Breakfast Cereals",
  "Frozen Veggies & Snacks",
  "Fruit Juices & Drinks",
  "Cookies, Rusk & Khari",
  "Fragrances & Deos",
  "Tea",
  "Masalas & Spices",
  "Men's Grooming",
  "Chocolates & Candies",
  "Steel Utensils",
  "Tinned & Processed Food",
  "Organic Staples",
  "Sauces, Spreads & Dips",
  "Pickles & Chutney",
  "Ready To Cook & Eat",
  "Baby Bath & Hygiene",
  "Pet Food & Accessories",
  "Biscuits & Cookies",
  "Oral Care",
  "Snacks & Namkeen",
  "Cookware & Non Stick",
  "Dairy",
  "Diapers & Wipes",
  "Baby Food & Formula",
  "Edible Oils & Ghee",
  "Crockery & Cutlery",
  "Oils & Vinegar",
  "Feminine Hygiene",
  "Feeding & Nursing",
  "Stationery",
  "Energy & Soft Drinks",
  "Appliances & Electricals",
  "Salt, Sugar & Jaggery",
  "Gourmet Breads",
  "Indian Mithai",
  "Health & Medicine",
  "Disposables, Garbage Bag",
  "Noodle, Pasta, Vermicelli",
  "Dals & Pulses",
  "Rice & Rice Products",
  "Spreads, Sauces, Ketchup",
  "Cereals & Breakfast",
  "Party & Festive Needs",
  "Health Drink, Supplement",
  "Non Dairy",
  "Bakeware",
  "Baby Accessories",
  "Coffee",
  "Makeup",
  "Detergents & Dishwash",
  "Atta, Flours & Sooji",
  "Car & Shoe Care",
  "Cakes & Pastries",
  "Gardening",
  "Ice Creams & Desserts",
  "Water",
  "Mothers & Maternity",
  "Bakery Snacks",
  "Cuts & Sprouts",
];
